[project]
name = "fish-market"
version = "0.1.0"
description = "Telegram bot for fish shop (Devman project)"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "python-dotenv>=1.2.1",
    "python-telegram-bot>=22.5",
    "redis>=7.1.0",
    "ruff>=0.14.7",
]
